block parser app-cef-netscout_arbor-edge() {
    channel {
        rewrite {
            set("${.metadata.cef.deviceHostName}" value(".splunk.host"));
        };
        rewrite {
            r_set_splunk_dest_update_v2(
                index('netids'),
                sourcetype('netscout:aed')
                template('t_msg_only')
            );
        };

    };
};
application app-cef-netscout_arbor-edge[cef] {
	filter{
        "${.metadata.cef.device_vendor}" eq "NETSCOUT"
        and ( "${.metadata.cef.device_product}" eq "Arbor Enterprise Manager" 
                or "${.metadata.cef.device_product}" eq "Arbor Edge Defense"
                or "${.metadata.cef.device_product}" eq "Arbor Networks APS"
        );
    };
    parser { app-cef-netscout_arbor-edge(); };
};
