#!/bin/bash
# filepath: configuration-tool.sh

# SC4S Configuration Tool
# Generates a customized env_file based on user requirements

set -e

# Colors for better UX
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Initialize variables
OUTPUT_FILE="env_file"
SPLUNK_URL=""
HEC_TOKEN=""
TLS_VERIFY="yes"
EXPECTED_EPS=1000
PROTOCOL="both"
UDP_SOCKETS=2
TCP_SOCKETS=2
PARALLELIZE="no"
VPS_CACHE="yes"

echo -e "${BLUE}================================================${NC}"
echo -e "${BLUE}    SC4S Configuration Tool${NC}"
echo -e "${BLUE}================================================${NC}"
echo ""
echo "This tool will help you generate an optimized SC4S configuration"
echo "based on your environment requirements."
echo ""

# Function to ask yes/no questions
ask_yes_no() {
    local question="$1"
    local default="$2"
    local response
    
    while true; do
        if [[ "$default" == "yes" ]]; then
            read -p "$question [Y/n]: " response
            response=${response:-y}
        else
            read -p "$question [y/N]: " response
            response=${response:-n}
        fi
        
        case "$response" in
            [Yy]* ) echo "yes"; break;;
            [Nn]* ) echo "no"; break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

echo -e "${GREEN}=== Splunk Configuration ===${NC}"

# Splunk HEC URL
read -p "Enter your Splunk HEC URL (e.g., https://your.splunk.instance:8088): " SPLUNK_URL

# HEC Token
read -p "Enter your Splunk HEC Token: " HEC_TOKEN

# TLS Verification
TLS_VERIFY=$(ask_yes_no "Verify SSL/TLS certificates?" "yes")

echo ""
echo -e "${GREEN}=== Performance Configuration ===${NC}"

# Expected EPS
read -p "Expected events per second (EPS) [1000]: " input_eps
EXPECTED_EPS=${input_eps:-1000}

# Protocol selection
echo ""
echo "Protocol preferences:"
echo "1) UDP only (faster, may lose messages)"
echo "2) TCP only (reliable, slower)"
echo "3) Both UDP and TCP (recommended)"
read -p "Select protocol [3]: " protocol_choice
protocol_choice=${protocol_choice:-3}
case "$protocol_choice" in
    1) PROTOCOL="udp";;
    2) PROTOCOL="tcp";;
    3) PROTOCOL="both";;
    *) PROTOCOL="both";;
esac

# Calculate optimal settings based on EPS
if [ "$EXPECTED_EPS" -gt 10000 ]; then
    UDP_SOCKETS=4
    TCP_SOCKETS=4
    PARALLELIZE="yes"
    echo -e "${YELLOW}High EPS detected (${EXPECTED_EPS}), enabling performance optimizations${NC}"
elif [ "$EXPECTED_EPS" -gt 5000 ]; then
    UDP_SOCKETS=3
    TCP_SOCKETS=3
    PARALLELIZE="yes"
    echo -e "${YELLOW}Medium-high EPS detected (${EXPECTED_EPS}), using moderate optimizations${NC}"
elif [ "$EXPECTED_EPS" -gt 1000 ]; then
    UDP_SOCKETS=2
    TCP_SOCKETS=2
    PARALLELIZE="no"
fi

# Advanced options
echo ""
echo -e "${GREEN}=== Advanced Options ===${NC}"

# Socket overrides
if [[ "$PROTOCOL" == "udp" || "$PROTOCOL" == "both" ]]; then
    read -p "UDP listen sockets [$UDP_SOCKETS]: " input_udp
    UDP_SOCKETS=${input_udp:-$UDP_SOCKETS}
fi

if [[ "$PROTOCOL" == "tcp" || "$PROTOCOL" == "both" ]]; then
    read -p "TCP listen sockets [$TCP_SOCKETS]: " input_tcp
    TCP_SOCKETS=${input_tcp:-$TCP_SOCKETS}
fi

# Parallelization
PARALLELIZE=$(ask_yes_no "Enable parallelization?" "$PARALLELIZE")

# VPS Cache
VPS_CACHE=$(ask_yes_no "Enable Vendor/Product/Source cache for better performance?" "$VPS_CACHE")

# Output file
echo ""
read -p "Output filename [$OUTPUT_FILE]: " input_output
OUTPUT_FILE=${input_output:-$OUTPUT_FILE}

# Generate configuration
echo ""
echo -e "${BLUE}Generating configuration...${NC}"

cat > "$OUTPUT_FILE" << EOF
# SC4S Configuration - Generated by configuration tool
# Expected EPS: $EXPECTED_EPS
# Protocol: $PROTOCOL
# Generated on: $(date)

# === Splunk HEC Configuration ===
SC4S_DEST_SPLUNK_HEC_DEFAULT_URL=$SPLUNK_URL
SC4S_DEST_SPLUNK_HEC_DEFAULT_TOKEN=$HEC_TOKEN
EOF

if [ "$TLS_VERIFY" == "no" ]; then
    cat >> "$OUTPUT_FILE" << EOF
SC4S_DEST_SPLUNK_HEC_DEFAULT_TLS_VERIFY=no
EOF
fi

cat >> "$OUTPUT_FILE" << EOF

# === Performance Configuration ===
EOF

if [[ "$PROTOCOL" == "udp" || "$PROTOCOL" == "both" ]]; then
    cat >> "$OUTPUT_FILE" << EOF
SC4S_SOURCE_LISTEN_UDP_SOCKETS=$UDP_SOCKETS
EOF
    
    if [ "$EXPECTED_EPS" -gt 5000 ]; then
        cat >> "$OUTPUT_FILE" << EOF
SC4S_SOURCE_UDP_SO_RCVBUFF=17039360
EOF
    fi
fi

if [[ "$PROTOCOL" == "tcp" || "$PROTOCOL" == "both" ]]; then
    cat >> "$OUTPUT_FILE" << EOF
SC4S_SOURCE_LISTEN_TCP_SOCKETS=$TCP_SOCKETS
EOF
fi

if [ "$PARALLELIZE" == "yes" ]; then
    cat >> "$OUTPUT_FILE" << EOF
SC4S_ENABLE_PARALLELIZE=yes
EOF
fi

if [ "$VPS_CACHE" == "yes" ]; then
    cat >> "$OUTPUT_FILE" << EOF
SC4S_USE_VPS_CACHE=yes
EOF
fi

# Add high-performance settings for very high EPS
if [ "$EXPECTED_EPS" -gt 10000 ]; then
    cat >> "$OUTPUT_FILE" << EOF

# === High Performance Settings ===
SC4S_SOURCE_TCP_IW_USE=yes
SC4S_SOURCE_TCP_IW_SIZE=1000000
SC4S_SOURCE_TCP_SO_RCVBUFF=17039360
EOF
fi

echo ""
echo -e "${GREEN}✓ Configuration generated successfully!${NC}"
echo -e "File: ${YELLOW}$OUTPUT_FILE${NC}"
echo ""
echo -e "${BLUE}Configuration Summary:${NC}"
echo "  Splunk URL: $SPLUNK_URL"
echo "  Protocol: $PROTOCOL"
echo "  Expected EPS: $EXPECTED_EPS"
echo "  UDP Sockets: $UDP_SOCKETS"
echo "  TCP Sockets: $TCP_SOCKETS"
echo "  Parallelization: $PARALLELIZE"
echo "  VPS Cache: $VPS_CACHE"
echo "  TLS Verify: $TLS_VERIFY"
echo ""
echo -e "${BLUE}To use this configuration:${NC}"
echo "  docker run --env-file $OUTPUT_FILE -p 514:514/udp -p 514:514/tcp sc4s:latest"
echo ""
echo -e "${GREEN}Configuration tool completed successfully!${NC}"