rewrite set_rfc3164_guardicore_centra{
    set-tag("wireformat:rfc3164_guardicore_centra");
};

filter f_is_rfc3164_guardicore_centra{
    tags("wireformat:rfc3164_guardicore_centra");
};

block parser app-almost-syslog-guardicore_centra() {
    channel {
        parser {
            regexp-parser(
                prefix(".tmp.")
                patterns('^(?<pri>\<\d+\>) ?(?<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?(?:Z|[+-]\d{2}:?\d{2})?) (?<host>[^ ]+) (?<message>CEF:0.*)')
            );
            date-parser(
                format(
                    '%Y-%m-%dT%H:%MZ'
                )
                template("${.tmp.timestamp}")
            );
            syslog-parser(
                flags(assume-utf8)
                template("${.tmp.pri} $S_ISODATE ${.tmp.host} ${.tmp.message}")
            );
        };
        rewrite(set_rfc);
        rewrite(set_rfc3164);
        rewrite(set_rfc3164_guardicore_centra);
    };
};

application app-almost-syslog-guardicore_centra[sc4s-almost-syslog] {
    filter {
        message('CEF:0|Guardicore|Centra|' type(string) flags(substring));
    };
    parser { app-almost-syslog-guardicore_centra(); };
};
