block parser app-syslog-dell_ome() {
    channel {
        parser {
            regexp-parser(
                patterns('\{\s*HostName\s*\}\s+(?<extracted_hostname>[A-Za-z0-9_\-]+)')
                template("${MESSAGE}")
            );
        };
        parser {
            regexp-parser(
                patterns('\{\s*IP\s*\}\s+(?<idrac_ip>[^\s\}]+)')
                template("${MESSAGE}")
            );
            regexp-parser(
                patterns('\{\s*Severity\s*\}\s+(?<idrac_severity>[^\s\}]+)')
                template("${MESSAGE}")
            );
            regexp-parser(
                patterns('\{\s*MessageID\s*\}\s+(?<idrac_messageid>[^\s\}]+)')
                template("${MESSAGE}")
            );
        };
        rewrite {
            r_set_splunk_dest_default(
                index('infraops')
                sourcetype('dell:ome')
                vendor('dell')
                product('ome')
                class('msc')
            );
        };
        rewrite {
            set("${extracted_hostname}", value("HOST"));
            set("${idrac_ip}", value("fields.idrac_ip"));
            set("${idrac_severity}", value("fields.idrac_severity"));
            set("${idrac_messageid}", value("fields.idrac_messageid"));
        };
    };
};

application app-syslog-dell_ome[sc4s-syslog] {
    filter {
        match(
            'EEMI.*\{\s*IP\s*\}.*\{\s*HostName\s*\}.*\{\s*Severity\s*\}.*\{\s*MessageID\s*\}.*' value("MESSAGE")
        );
    };
    parser { app-syslog-dell_ome(); };
};
