block parser app-netsource-dell_powerstore() {
 channel {
        rewrite {
            r_set_splunk_dest_default(
                index('netops')
                sourcetype('dell:emc:powerstore')
                vendor('dellemc')
                product('powerstore')
            );
        };
    };
};
application app-netsource-dell_powerstore[sc4s-network-source] {
    filter {
            ("${.netsource.sc4s_vendor_product}" eq "dellemc_powerstore"
            or "${SOURCE}" eq "s_DELLEMC_POWERSTORE")
            and "${fields.sc4s_vendor_product}" eq ""
        };
	parser { app-netsource-dell_powerstore(); };
};