application app-vps-dell_powerstore[sc4s-vps] {
    filter {
        host("test-dell-powerstore" type(string) flags(prefix))
    }; 
    parser { 
        p_set_netsource_fields(
            vendor('dellemc')
            product('powerstore')
        ); 
    };   
};
