log {
    if {
        filter(f_host_is_nil_or_ip);
    } elif {
        filter {
            match("^(true|1|t|y|yes)$" template("`SC4S_USE_NAME_CACHE`") flags(ignore-case))
        };
        destination(d_psc);
    };
    flags(catchall);
};