import subprocess
from unittest.mock import MagicMock, patch

from tools.configurator_tools import sc4s_build_config


VALID_URL = "https://splunk.example.com:8088"
VALID_TOKEN = "12345678-1234-1234-1234-123456789abc"

SAMPLE_CONFIG = """# SC4S Configuration - Generated by configuration tool
# Mode: Custom configuration
# Expected EPS: 1000
# Protocol: both
# Generated on: Tue Jul  1 00:00:00 UTC 2026

# === Splunk HEC Configuration ===
SC4S_DEST_SPLUNK_HEC_DEFAULT_URL=https://splunk.example.com:8088
SC4S_DEST_SPLUNK_HEC_DEFAULT_TOKEN=12345678-1234-1234-1234-123456789abc

# === Performance Configuration ===
"""


def _make_proc(stdout: str = SAMPLE_CONFIG, returncode: int = 0, stderr: str = "") -> MagicMock:
    """Return a mock CompletedProcess."""
    proc = MagicMock()
    proc.stdout = stdout
    proc.returncode = returncode
    proc.stderr = stderr
    return proc


# ---------------------------------------------------------------------------
# Happy-path tests
# ---------------------------------------------------------------------------


@patch("tools.configurator_tools.subprocess.run")
def test_generate_config_valid_inputs(mock_run):
    """Valid hec_url and hec_token should call subprocess and return its stdout."""
    mock_run.return_value = _make_proc()

    result = sc4s_build_config(hec_url=VALID_URL, hec_token=VALID_TOKEN)

    mock_run.assert_called_once()
    assert result == SAMPLE_CONFIG


@patch("tools.configurator_tools.subprocess.run")
def test_generate_config_passes_env_vars(mock_run):
    """Env vars should be forwarded to the subprocess correctly."""
    mock_run.return_value = _make_proc()

    sc4s_build_config(
        hec_url=VALID_URL,
        hec_token=VALID_TOKEN,
        tls_verify="no",
        protocol="udp",
        mode="custom",
        expected_eps=5000,
        default_timezone="America/New_York",
    )

    _, kwargs = mock_run.call_args
    env = kwargs["env"]
    assert env["SC4S_NON_INTERACTIVE"] == "1"
    assert env["SC4S_HEC_URL"] == VALID_URL
    assert env["SC4S_HEC_TOKEN"] == VALID_TOKEN
    assert env["SC4S_TLS_VERIFY"] == "no"
    assert env["SC4S_PROTOCOL"] == "udp"
    assert env["SC4S_MODE"] == "custom"
    assert env["SC4S_EXPECTED_EPS"] == "5000"
    assert env["SC4S_DEFAULT_TIMEZONE"] == "America/New_York"


@patch("tools.configurator_tools.subprocess.run")
def test_generate_config_hardware_mode(mock_run):
    """Hardware mode should include SC4S_HARDWARE and SC4S_MODE=hardware in env."""
    mock_run.return_value = _make_proc()

    sc4s_build_config(
        hec_url=VALID_URL,
        hec_token=VALID_TOKEN,
        mode="hardware",
        hardware="16vCPUs",
        expected_eps=50000,
    )

    _, kwargs = mock_run.call_args
    env = kwargs["env"]
    assert env["SC4S_MODE"] == "hardware"
    assert env["SC4S_HARDWARE"] == "16vCPUs"
    assert env["SC4S_EXPECTED_EPS"] == "50000"


@patch("tools.configurator_tools.subprocess.run")
def test_generate_config_tuning_overrides_included(mock_run):
    """Non-zero tuning overrides should be forwarded as env vars."""
    mock_run.return_value = _make_proc()

    sc4s_build_config(
        hec_url=VALID_URL,
        hec_token=VALID_TOKEN,
        source_udp_fetch_limit=500000,
        source_listen_udp_sockets=32,
        enable_ebpf="yes",
        ebpf_no_sockets=8,
        enable_parallelize="yes",
        parallelize_no_partition=4,
    )

    _, kwargs = mock_run.call_args
    env = kwargs["env"]
    assert env["SC4S_SOURCE_UDP_FETCH_LIMIT"] == "500000"
    assert env["SC4S_SOURCE_LISTEN_UDP_SOCKETS"] == "32"
    assert env["SC4S_ENABLE_EBPF"] == "yes"
    assert env["SC4S_EBPF_NO_SOCKETS"] == "8"
    assert env["SC4S_ENABLE_PARALLELIZE"] == "yes"
    assert env["SC4S_PARALLELIZE_NO_PARTITION"] == "4"


@patch("tools.configurator_tools.subprocess.run")
def test_generate_config_zero_overrides_not_forwarded(mock_run):
    """Zero-value overrides should NOT be included in the subprocess env."""
    mock_run.return_value = _make_proc()

    sc4s_build_config(hec_url=VALID_URL, hec_token=VALID_TOKEN)

    _, kwargs = mock_run.call_args
    env = kwargs["env"]
    assert "SC4S_SOURCE_UDP_FETCH_LIMIT" not in env
    assert "SC4S_EBPF_NO_SOCKETS" not in env
    assert "SC4S_SOURCE_TCP_SO_RCVBUFF" not in env


# ---------------------------------------------------------------------------
# Validation error tests — subprocess must NOT be called
# ---------------------------------------------------------------------------


@patch("tools.configurator_tools.subprocess.run")
def test_invalid_hec_url_returns_error(mock_run):
    """An invalid HEC URL should return an error without calling subprocess."""
    result = sc4s_build_config(hec_url="not-a-url", hec_token=VALID_TOKEN)

    mock_run.assert_not_called()
    assert result.startswith("Error:")
    assert "hec_url" in result


@patch("tools.configurator_tools.subprocess.run")
def test_invalid_hec_url_missing_scheme_returns_error(mock_run):
    """A URL without http/https scheme should return an error without calling subprocess."""
    result = sc4s_build_config(
        hec_url="splunk.example.com:8088", hec_token=VALID_TOKEN
    )

    mock_run.assert_not_called()
    assert result.startswith("Error:")


@patch("tools.configurator_tools.subprocess.run")
def test_invalid_hec_token_returns_error(mock_run):
    """A non-UUID HEC token should return an error without calling subprocess."""
    result = sc4s_build_config(hec_url=VALID_URL, hec_token="not-a-uuid")

    mock_run.assert_not_called()
    assert result.startswith("Error:")
    assert "hec_token" in result


@patch("tools.configurator_tools.subprocess.run")
def test_invalid_hec_token_partial_uuid_returns_error(mock_run):
    """A partial UUID should return an error without calling subprocess."""
    result = sc4s_build_config(hec_url=VALID_URL, hec_token="12345678-1234-1234")

    mock_run.assert_not_called()
    assert result.startswith("Error:")


# ---------------------------------------------------------------------------
# Subprocess failure tests
# ---------------------------------------------------------------------------


@patch("tools.configurator_tools.subprocess.run")
def test_script_nonzero_exit_returns_error(mock_run):
    """Non-zero exit code should return an error string."""
    mock_run.return_value = _make_proc(
        stdout="", returncode=1, stderr="SC4S_HEC_URL is required"
    )

    result = sc4s_build_config(hec_url=VALID_URL, hec_token=VALID_TOKEN)

    assert result.startswith("Error:")
    assert "1" in result  # exit code


@patch("tools.configurator_tools.subprocess.run", side_effect=FileNotFoundError)
def test_script_not_found_returns_error(mock_run):
    """Missing script file should return a descriptive error."""
    result = sc4s_build_config(hec_url=VALID_URL, hec_token=VALID_TOKEN)

    assert result.startswith("Error:")
    assert "not found" in result


@patch(
    "tools.configurator_tools.subprocess.run",
    side_effect=subprocess.TimeoutExpired(cmd="bash", timeout=30),
)
def test_script_timeout_returns_error(mock_run):
    """Subprocess timeout should return a descriptive error."""
    result = sc4s_build_config(hec_url=VALID_URL, hec_token=VALID_TOKEN)

    assert result.startswith("Error:")
    assert "timed out" in result
