name: mike
on:
  push:
    branches:
      - "main"
      - "releases/*"
      - "develop"
      - "next*"
    tags-ignore:
      - "*beta*"
      - "*next*"

jobs:
  mike:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - uses: oleksiyrudenko/gha-git-credentials@8bb1fe6d543b2233ef1856cd3b0181f5abbd4d6a # v2.1.2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: Upload
        run: |
          BRANCH=$(echo $GITHUB_REF | cut -d / -f 3)
          echo $BRANCH
          python -m pip install --upgrade pip==26.0
          pip3 install --only-binary :all: poetry
          poetry install
          poetry run mike deploy -p $BRANCH