name: Release Tagger

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.e"

permissions:
  actions: read
  contents: write

jobs:
  update-semver-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Update Semver Tags
        uses: tchupp/actions-update-semver-tags@bc82481a87e4e95cd38bab00d566bcc49cea970f # v1.0.2
